api/README.md, api/go.mod, api/go.sum, api/grpcgateway/http_status.go, api/interceptor/interceptor.go, api/interceptor/observer.go, api/interceptor/observer_connectrpc.go, api/interceptor/observer_http.go, api/interceptor/observer_test.go, api/metrics/options.go, api/metrics/prometheus.go
This PR adds an observer interceptor and a helper 
1. An observer interceptor which observes (streaming) requests from beginning to end and call a provided callback function with stats collected when processing the request
2. A Prometheus helper, which can be used to instrument an API server. It's supposed to be used alongside the observer interceptor to collect metrics.
Example prometheus metrics:
```
request_duration_seconds_bucket{procedure="/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo",status="ok",test="val",le="0.005"} 3
request_duration_seconds_bucket{procedure="/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo",status="ok",test="val",le="0.01"} 4
request_duration_seconds_bucket{procedure="/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo", …
```
=> backend: add observer and metrics interceptor

.gitignore, rpadmin/admin.go, rpadmin/api_debug.go, rpadmin/api_partition.go, rpadmin/api_security.go, rpadmin/api_transform.go
We are working to migrate rpk finally to common-go, since the repo was created we've added a few endpoints that we need once we migrate. This PR includes a commit-by-commit history of all the endpoints that are being added.
For more information on them, you can also check all the changes here https://github.com/redpanda-data/redpanda/commits/dev/src/go/rpk/pkg/adminapi since `5080bd3`
=> rpadmin: feature parity with rpk

rpadmin/api_partition.go
Wrapper of the new `POST /v1/partitions/<namespace>/<topic>/<partition>/replicas/<node>` endpoint, will be used to fix https://github.com/redpanda-data/redpanda/issues/21562
=> rpadmin: add UpdatePartitionReplicaCore method

rpadmin/api_config.go
`rpk cluster config get` requests only a single cluster property from `redpanda`.
However, currently we return the entire JSON of the cluster properties to `rpk`, and then parse the desired property from there.
To support retrieving only a single value from the cluster properties (and also to support aliased properties in the future), add `singleKeyConfig()`, which uses a string to be used as the query parameter `key` to the `redpanda` admin endpoint.
=> `rpadmin`: add `SingleKeyConfig()`

rpadmin/api_partition.go
Wrapper of the existing `POST /v1/partitions/rebalance` endpoint. This is required for https://github.com/redpanda-data/redpanda/pull/22855.
=> rpadmin: add TriggerBalancer method

rpadmin/admin.go
This adds the ability to specify a custom dialer implementation for the `AdminAPI` client. I plan on pairing it with https://github.com/redpanda-data/helm-charts/pull/1484 so that we can do things like port-forwarded dials to our brokers/admin APIs _as if_ we were inside of a container (i.e. our controllers) and issuing requests.
=> Add ability to set client dialer

.github/workflows/golangci-lint.yaml, .golangci.yaml, Taskfile.yaml, rpadmin/api_migration.go, rpadmin/api_migration_test.go, rpadmin/api_partition.go
Adds support for migrations to the admin api
=> feat: adds support for migrations

rpadmin/api_features.go
It was unclear to the caller what to pass to the
SetLicense method. It was any because it was a
carryover from rpk, but we should use stricter
typing in our methods.
WARNING: This is a breaking change of the API, however, the only known caller is rpk, which already passes an `io.Reader` https://github.com/redpanda-data/redpanda/blob/dev/src/go/rpk/pkg/cli/cluster/license/set.go#L51.
=> rpadmin: change SetLicense input from any to io.Reader

rpadmin/api_debug.go
This commit adds the `RestartService` method to `AdminAPI` as documented [here](https://docs.redpanda.com/api/admin-api/#put-/v1/debug/restart_service).
=> rpadmin: add `RestartService`

rpadmin/admin.go
This allows for setting auth credentials on a client after it's initialized.
=> Allow for setting auth on admin client

rpadmin/api_broker.go
This commit adds additional field to the `Broker`
struct in `api_broker.go`. This will be used in
'rpk redpanda admin brokers list' to print those
info additionally.
=> rpadmin: expose rack,host,port,uuid info via api_broker

rpadmin/api_mount.go
Fixes baseMountEndpoint to baseMountableEndpoint.
=> fix: add mountable endpoint

rpadmin/api_migration.go, rpadmin/api_migration_test.go, rpadmin/api_mount.go
The returned migration may be an inbound or outbound migration. Depending on the type the schema is different as per: https://github.com/redpanda-data/redpanda/blob/40e0dcab0303ccc8a38cbb30b327723aa9d3964d/src/v/redpanda/admin/api-doc/migration.json#L17-L23
This change reflects that behaviour.
=> rpadmin: support namespaced and inbound topic in migration state

secrets/aws.go, secrets/go.mod
This is needed when secrets are not directly accessible by the main service account.
=> secrets: allow AWS client to assume a different role

rpadmin/admin.go
This allows for creating a "scoped" client that talks only to the given broker, but with the same TLS and auth settings as the previous client. It adds methods for scoping a client to a broker by host URL and for scoping via Broker ID.
=> Scope clients to new hosts

rpadmin/admin.go, rpadmin/admin_test.go, rpadmin/api_debug.go
This ensures that we close all response bodies (or documents when they should be closed, but aren't). Working on some tests/validations, but throwing this up here for some eyes.
=> Close leaked response bodies

rpadmin/admin.go, rpadmin/admin_test.go
This PR does a couple of things:
1. It limits the amount of connections we actually allow the undelrying `http.Transport` to initialize in the rpadmin client and sets some sane defaults based for idle connection timeouts based off of `http.DefaultTransport`
2. It introduces a `Close` method that flushes all idle connections in the connection pool. This allows us to manually close all pooled connections when a client is no longer needed.
=> Add cleanup routines for underlying http transport

rpadmin/admin.go, rpadmin/admin_test.go, rpadmin/api_partition.go
This adds support for the [`/v1/partitions/local_summary`](https://docs.redpanda.com/api/admin-api/#get-/v1/partitions/local_summary) endpoint.
Additionally, it fixes and issue with attempting to use the newly introduced mechanism to create a scoped client leveraging `ForBroker`. Specifically, when attempting to map a broker id to URL, the code [initializes](https://github.com/redpanda-data/common-go/blob/05ac5889aee7acab24333d9cdbba23f8f25285a1/rpadmin/admin.go#L577) a "single host" client. When passing a custom dialer to the parent client, this dialer was no longer used in the subclients, which, in the Kubernetes test case where we use a dialer that is actually opening up port-forwarded connections, means that we immediately fail to resolve the Kubernetes DNS host we're attempting to …
=> Add local partition summary support and fix dialer usage when leveraging ForBroker and the like

rpadmin/api_features.go
The license retrievel request works without any authentication, but the request to figure out the leader requires authentication. The get license request can be send to any node though.
=> rpadmin: get license info from any node

.github/workflows/golangci-lint.yaml
The current version is incompatible with Go 1.24
=> chore: update golangci lint to 1.64

.github/workflows/golangci-lint.yaml, rpadmin/api_broker.go, rpadmin/api_features.go, rpadmin/api_migration.go
And also fixes a typo in the `.github` directory path that prevented the CI from picking up changes in the dir to trigger the linter job.
=> rpadmin: fix linter issues in `rpadmin`

rpadmin/api_broker.go
Redpanda core starts exposing reallocation failed partition details in https://github.com/redpanda-data/redpanda/pull/26054
This commit adds the corresponding func in api_broker.go to support the feature in rpk.
=> rpadmin: Add ReallocationFailedPartition to api_broker

taskfiles/proto.yaml
- Upgrades buf version from 1.39.0 to 1.55.1 for latest features and bug fixes
- Adds --git-metadata flag to buf push command for better tracking of schema registry changes
=> Update buf tooling configuration

proto/redpanda/api/common/v1/errordetails.proto, proto/redpanda/api/common/v1/money.proto, proto/redpanda/api/common/v1/options.proto, proto/redpanda/api/common/v1/pagination.proto, proto/redpanda/api/common/v1alpha1/common.proto, proto/redpanda/api/common/v1alpha1/options.proto
- Migrate all common proto types from v1alpha1 to v1 to complete API stabilization
- Add missing types to v1: Reason enum, ErrorStatus message, Money message, Currency enum, required_permission extension, KeySetPageToken message  
- Mark all v1alpha1 proto files as deprecated with upgrade guidance
This migration ensures all shared types are available in the stable API while maintaining backward compatibility.
=> proto: migrate common types from v1alpha1 to stable v1 API

proto/redpanda/api/common/v1/options.proto
- Fixed protobuf extension tag conflict between v1 and v1alpha1 options.proto files
- Changed extension tag from 15350 to 15351 in v1/options.proto to resolve buf lint error
=> Fix protobuf extension tag conflict

rpsr/builder.go, rpsr/builder_test.go, rpsr/go.mod, rpsr/go.sum, rpsr/rpsr.go, rpsr/rpsr_test.go
This is a client wrapper that extends the franz-go sr client to handle the upcoming Schema Registry ACL endpoints.
It includes a helper ACLBuilder, which allows an ergonomic way of handling ACL creations with optional defaults. The interface and errors are similar to the franz-go acl package, with the difference that here we do not assume any default value and it must be specified.
=> rpsr: add rpsr package, Redpanda Schema registry

.github/workflows/golangci-lint.yaml, .github/workflows/test.yaml
This PR adds:
- Tests (go run ./...) when a Go file changes.
- Added `rpsr` to golangci-lint jobs
- Added a matrix strategy to make it easier to add new directories to our current jobs.
=> gha: add Go tests, add matrix jobs for golangci

rpsr/rpsr.go
Prevents a panic if using the method directly (this doesn't happen when using ListACLBatch).
=> rpsr: avoid adding to ctx if filter is nil

rpsr/rpsr.go, rpsr/rpsr_test.go
Fixes a string normalization error where we were stripping the underscore but comparing against it:
`normalize(describe_config)` -> describeconfig -> compared against `describe_config`
=> rpsr: fix string normalization

rpadmin/api_config.go
We are looking to add the ability to obtain the current log level for 1 or more loggers using rpk. This PR adds the ability to get this information using the /v1/loggers endpoint. With the include-levels=true param, it will return all loggers and the level they are currently set to.
=> feature: adding ability to call /v1/loggers endpoint to use in rpk
